stages:
  - build

python:
  stage: build
  image: python:latest
  script:
    - adduser --disabled-password --gecos "" user
    - run_tests="poetry run pytest --doctest-modules rule_one.py test_rule_one.py"
    - su user -c "pip install --user poetry"
    - su user -c "$run_tests"
