stages:
  - test

test:
  stage: test
  image: python:latest
  script:
    - poetry run pytest --doctest-modules rule_one.py test_rule_one.py

# Enable caching of Poetry dependencies.
before_script:
  - adduser --disabled-password --gecos "" user
  - su --login user
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="$HOME/.local/bin:$PATH"
  - poetry config virtualenvs.in-project true
  - poetry install

cache:
  paths:
    - .venv
