stages:
  - test

test:
  stage: test
  image: python:latest
  script:
    - adduser --disabled-password --gecos "" user
    - su user -c "pip install --user poetry"
    - su user -c "$HOME/.local/bin/poetry run pytest --doctest-modules rule_one.py test_rule_one.py"
