stages:
  - test

test:
  stage: test
  image: python:latest
  script:
    - poetry run pytest --doctest-modules rule_one.py test_rule_one.py

# Enable caching of Poetry dependencies.
before_script:
  - user=user
  - adduser --disabled-password --gecos "" "$user"
  - su --login "$user"
  - export PATH="$HOME/.local/bin:$PATH"
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry config virtualenvs.in-project true
  # Fix error with building numpy.
  - poetry config experimental.new-installer false
  - poetry install

cache:
  paths:
    - .venv
